//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/My.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @My: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @My()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""My"",
    ""maps"": [
        {
            ""name"": ""GraphicsSett"",
            ""id"": ""8055f9de-0e2c-4bd9-be30-d25b2a120f66"",
            ""actions"": [
                {
                    ""name"": ""Graphics1"",
                    ""type"": ""Button"",
                    ""id"": ""7f445580-30bb-45ef-970c-1c3d840e8d8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graphics2"",
                    ""type"": ""Button"",
                    ""id"": ""10946f04-8705-41b3-aa1e-0fb3e49ae83e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graphics3"",
                    ""type"": ""Button"",
                    ""id"": ""8c3497c2-ee6d-46d9-aa6e-6c284b669b46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graphics4"",
                    ""type"": ""Button"",
                    ""id"": ""f63cb37e-51e3-40ab-b9fb-ab727bfa5f8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graphics5"",
                    ""type"": ""Button"",
                    ""id"": ""ec888506-ab5a-465d-acb9-963e86544eff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graphics6"",
                    ""type"": ""Button"",
                    ""id"": ""8b5bea76-cd36-464a-baa2-5188b398e8de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Beep"",
                    ""type"": ""Button"",
                    ""id"": ""7dcf3321-47a5-4676-a03a-443e8a9ad059"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HandB"",
                    ""type"": ""Button"",
                    ""id"": ""c9453fa3-d041-4065-a3f0-e983f8f41bdb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpaceBtt"",
                    ""type"": ""Button"",
                    ""id"": ""80535749-6bf8-4e3c-bb17-47b9b84e9fb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tormoz"",
                    ""type"": ""Button"",
                    ""id"": ""e3ca8439-5fc3-4a49-a3b3-e1006f551378"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B_Key"",
                    ""type"": ""Button"",
                    ""id"": ""ae2e74ff-453f-45f9-802d-ea5f47dc20f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Automat"",
                    ""type"": ""Button"",
                    ""id"": ""fc306b46-8b72-4955-a244-ae4ee774dea9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a1a93f5a-dc84-4808-9eed-72726ffab9c3"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graphics1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c2b19eb-afe9-42c7-9a78-5d80535bcdd6"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graphics2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""102a53fa-d9ac-4b78-bdfc-243693cd5efd"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graphics3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0308d72-1afc-4939-a445-76283eb6fac3"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graphics4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3362c575-6360-41ca-b48e-b2d3d783973d"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graphics5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c09c8040-6c9f-41c5-9e8b-af1bf60e5135"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Graphics6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0257679b-bfa4-46a1-b5e0-9841cbda16a5"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Beep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4be0d054-8704-4c1c-9afb-6025cf5e75bf"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1786a05-7fe9-4fb2-93db-862b867b342d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceBtt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45ff3f5c-158e-405f-9f02-57be7d5fcced"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tormoz"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a66570c-c4b8-4f67-8d7c-11d28281c747"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B_Key"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea5c0023-01f9-4615-9245-501b5232bb3f"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Automat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GraphicsSett
        m_GraphicsSett = asset.FindActionMap("GraphicsSett", throwIfNotFound: true);
        m_GraphicsSett_Graphics1 = m_GraphicsSett.FindAction("Graphics1", throwIfNotFound: true);
        m_GraphicsSett_Graphics2 = m_GraphicsSett.FindAction("Graphics2", throwIfNotFound: true);
        m_GraphicsSett_Graphics3 = m_GraphicsSett.FindAction("Graphics3", throwIfNotFound: true);
        m_GraphicsSett_Graphics4 = m_GraphicsSett.FindAction("Graphics4", throwIfNotFound: true);
        m_GraphicsSett_Graphics5 = m_GraphicsSett.FindAction("Graphics5", throwIfNotFound: true);
        m_GraphicsSett_Graphics6 = m_GraphicsSett.FindAction("Graphics6", throwIfNotFound: true);
        m_GraphicsSett_Beep = m_GraphicsSett.FindAction("Beep", throwIfNotFound: true);
        m_GraphicsSett_HandB = m_GraphicsSett.FindAction("HandB", throwIfNotFound: true);
        m_GraphicsSett_SpaceBtt = m_GraphicsSett.FindAction("SpaceBtt", throwIfNotFound: true);
        m_GraphicsSett_Tormoz = m_GraphicsSett.FindAction("Tormoz", throwIfNotFound: true);
        m_GraphicsSett_B_Key = m_GraphicsSett.FindAction("B_Key", throwIfNotFound: true);
        m_GraphicsSett_Automat = m_GraphicsSett.FindAction("Automat", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GraphicsSett
    private readonly InputActionMap m_GraphicsSett;
    private List<IGraphicsSettActions> m_GraphicsSettActionsCallbackInterfaces = new List<IGraphicsSettActions>();
    private readonly InputAction m_GraphicsSett_Graphics1;
    private readonly InputAction m_GraphicsSett_Graphics2;
    private readonly InputAction m_GraphicsSett_Graphics3;
    private readonly InputAction m_GraphicsSett_Graphics4;
    private readonly InputAction m_GraphicsSett_Graphics5;
    private readonly InputAction m_GraphicsSett_Graphics6;
    private readonly InputAction m_GraphicsSett_Beep;
    private readonly InputAction m_GraphicsSett_HandB;
    private readonly InputAction m_GraphicsSett_SpaceBtt;
    private readonly InputAction m_GraphicsSett_Tormoz;
    private readonly InputAction m_GraphicsSett_B_Key;
    private readonly InputAction m_GraphicsSett_Automat;
    public struct GraphicsSettActions
    {
        private @My m_Wrapper;
        public GraphicsSettActions(@My wrapper) { m_Wrapper = wrapper; }
        public InputAction @Graphics1 => m_Wrapper.m_GraphicsSett_Graphics1;
        public InputAction @Graphics2 => m_Wrapper.m_GraphicsSett_Graphics2;
        public InputAction @Graphics3 => m_Wrapper.m_GraphicsSett_Graphics3;
        public InputAction @Graphics4 => m_Wrapper.m_GraphicsSett_Graphics4;
        public InputAction @Graphics5 => m_Wrapper.m_GraphicsSett_Graphics5;
        public InputAction @Graphics6 => m_Wrapper.m_GraphicsSett_Graphics6;
        public InputAction @Beep => m_Wrapper.m_GraphicsSett_Beep;
        public InputAction @HandB => m_Wrapper.m_GraphicsSett_HandB;
        public InputAction @SpaceBtt => m_Wrapper.m_GraphicsSett_SpaceBtt;
        public InputAction @Tormoz => m_Wrapper.m_GraphicsSett_Tormoz;
        public InputAction @B_Key => m_Wrapper.m_GraphicsSett_B_Key;
        public InputAction @Automat => m_Wrapper.m_GraphicsSett_Automat;
        public InputActionMap Get() { return m_Wrapper.m_GraphicsSett; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GraphicsSettActions set) { return set.Get(); }
        public void AddCallbacks(IGraphicsSettActions instance)
        {
            if (instance == null || m_Wrapper.m_GraphicsSettActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GraphicsSettActionsCallbackInterfaces.Add(instance);
            @Graphics1.started += instance.OnGraphics1;
            @Graphics1.performed += instance.OnGraphics1;
            @Graphics1.canceled += instance.OnGraphics1;
            @Graphics2.started += instance.OnGraphics2;
            @Graphics2.performed += instance.OnGraphics2;
            @Graphics2.canceled += instance.OnGraphics2;
            @Graphics3.started += instance.OnGraphics3;
            @Graphics3.performed += instance.OnGraphics3;
            @Graphics3.canceled += instance.OnGraphics3;
            @Graphics4.started += instance.OnGraphics4;
            @Graphics4.performed += instance.OnGraphics4;
            @Graphics4.canceled += instance.OnGraphics4;
            @Graphics5.started += instance.OnGraphics5;
            @Graphics5.performed += instance.OnGraphics5;
            @Graphics5.canceled += instance.OnGraphics5;
            @Graphics6.started += instance.OnGraphics6;
            @Graphics6.performed += instance.OnGraphics6;
            @Graphics6.canceled += instance.OnGraphics6;
            @Beep.started += instance.OnBeep;
            @Beep.performed += instance.OnBeep;
            @Beep.canceled += instance.OnBeep;
            @HandB.started += instance.OnHandB;
            @HandB.performed += instance.OnHandB;
            @HandB.canceled += instance.OnHandB;
            @SpaceBtt.started += instance.OnSpaceBtt;
            @SpaceBtt.performed += instance.OnSpaceBtt;
            @SpaceBtt.canceled += instance.OnSpaceBtt;
            @Tormoz.started += instance.OnTormoz;
            @Tormoz.performed += instance.OnTormoz;
            @Tormoz.canceled += instance.OnTormoz;
            @B_Key.started += instance.OnB_Key;
            @B_Key.performed += instance.OnB_Key;
            @B_Key.canceled += instance.OnB_Key;
            @Automat.started += instance.OnAutomat;
            @Automat.performed += instance.OnAutomat;
            @Automat.canceled += instance.OnAutomat;
        }

        private void UnregisterCallbacks(IGraphicsSettActions instance)
        {
            @Graphics1.started -= instance.OnGraphics1;
            @Graphics1.performed -= instance.OnGraphics1;
            @Graphics1.canceled -= instance.OnGraphics1;
            @Graphics2.started -= instance.OnGraphics2;
            @Graphics2.performed -= instance.OnGraphics2;
            @Graphics2.canceled -= instance.OnGraphics2;
            @Graphics3.started -= instance.OnGraphics3;
            @Graphics3.performed -= instance.OnGraphics3;
            @Graphics3.canceled -= instance.OnGraphics3;
            @Graphics4.started -= instance.OnGraphics4;
            @Graphics4.performed -= instance.OnGraphics4;
            @Graphics4.canceled -= instance.OnGraphics4;
            @Graphics5.started -= instance.OnGraphics5;
            @Graphics5.performed -= instance.OnGraphics5;
            @Graphics5.canceled -= instance.OnGraphics5;
            @Graphics6.started -= instance.OnGraphics6;
            @Graphics6.performed -= instance.OnGraphics6;
            @Graphics6.canceled -= instance.OnGraphics6;
            @Beep.started -= instance.OnBeep;
            @Beep.performed -= instance.OnBeep;
            @Beep.canceled -= instance.OnBeep;
            @HandB.started -= instance.OnHandB;
            @HandB.performed -= instance.OnHandB;
            @HandB.canceled -= instance.OnHandB;
            @SpaceBtt.started -= instance.OnSpaceBtt;
            @SpaceBtt.performed -= instance.OnSpaceBtt;
            @SpaceBtt.canceled -= instance.OnSpaceBtt;
            @Tormoz.started -= instance.OnTormoz;
            @Tormoz.performed -= instance.OnTormoz;
            @Tormoz.canceled -= instance.OnTormoz;
            @B_Key.started -= instance.OnB_Key;
            @B_Key.performed -= instance.OnB_Key;
            @B_Key.canceled -= instance.OnB_Key;
            @Automat.started -= instance.OnAutomat;
            @Automat.performed -= instance.OnAutomat;
            @Automat.canceled -= instance.OnAutomat;
        }

        public void RemoveCallbacks(IGraphicsSettActions instance)
        {
            if (m_Wrapper.m_GraphicsSettActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGraphicsSettActions instance)
        {
            foreach (var item in m_Wrapper.m_GraphicsSettActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GraphicsSettActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GraphicsSettActions @GraphicsSett => new GraphicsSettActions(this);
    public interface IGraphicsSettActions
    {
        void OnGraphics1(InputAction.CallbackContext context);
        void OnGraphics2(InputAction.CallbackContext context);
        void OnGraphics3(InputAction.CallbackContext context);
        void OnGraphics4(InputAction.CallbackContext context);
        void OnGraphics5(InputAction.CallbackContext context);
        void OnGraphics6(InputAction.CallbackContext context);
        void OnBeep(InputAction.CallbackContext context);
        void OnHandB(InputAction.CallbackContext context);
        void OnSpaceBtt(InputAction.CallbackContext context);
        void OnTormoz(InputAction.CallbackContext context);
        void OnB_Key(InputAction.CallbackContext context);
        void OnAutomat(InputAction.CallbackContext context);
    }
}
